version: "3"
services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - my-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - my-network

  products:
    build:
      dockerfile: Dockerfile
      context: ./product-service
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "rabbitmq"
      - "mongodb"
    volumes:
      - ./product-service:/app
      - /app/node_modules
    networks:
      - my-network

  order:
    build:
      dockerfile: Dockerfile
      context: ./order-services
    container_name: order
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "rabbitmq"
      - "mongodb"
    volumes:
      - ./order-services:/app
      - /app/node_modules
    networks:
      - my-network

  auth:
    build:
      dockerfile: Dockerfile
      context: ./auth-server
    container_name: auth
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "mongodb"
    volumes:
      - ./auth-server:/app
      - /app/node_modules
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
